<?php
declare(strict_types=1);

return [
    'light' => [
        'hafenblau' => [
            'name' => 'Hafenblau',
            'color' => '#cfe0ec',
            'tokens' => [
                '--bg'                => '#dce8f0',
                '--surface'           => '#eaf3f8',
                '--border'            => '#b8d0e0',
                '--text-primary'      => '#0d3a5c',
                '--text-primary-dark' => '#0a2e48',
                '--text-secondary'    => '#3a7090',
                '--text-muted'        => '#7aaac0',
                '--accent'            => '#1a6090',
                '--done-bg'           => '#d0e5f0',
                '--error'             => '#c0392b',
                '--brand-mark-surface' => 'rgba(236, 246, 252, 0.94)',
                '--brand-mark-border' => 'rgba(25, 96, 144, 0.2)',
                '--brand-mark-shadow' => '0 14px 28px rgba(16, 72, 112, 0.2)',
                '--brand-mark-filter' => 'saturate(0.9) hue-rotate(8deg) contrast(1.02)',
                '--tab-icon-chip' => 'rgba(26, 96, 144, 0.14)',
                '--tab-icon-chip-active' => 'rgba(26, 96, 144, 0.3)',
                '--tab-icon-filter' => 'saturate(0.96) hue-rotate(4deg)',
                '--tab-icon-filter-active' => 'saturate(1.12) hue-rotate(6deg)',
            ],
        ],
        'parchment' => [
            'name' => 'Pergament',
            'color' => '#f5f0eb',
            'tokens' => [],
        ],
    ],
    'dark' => [
        'nachtwache' => [
            'name' => 'Nachtwache',
            'color' => '#162338',
            'tokens' => [
                '--bg'                => '#111c2d',
                '--surface'           => '#162338',
                '--border'            => '#1e3550',
                '--text-primary'      => '#cce4f4',
                '--text-primary-dark' => '#e0f0ff',
                '--text-secondary'    => '#4a80a8',
                '--text-muted'        => '#2d5070',
                '--accent'            => '#1a6090',
                '--done-bg'           => '#0d1828',
                '--error'             => '#e05050',
                '--brand-mark-surface' => 'linear-gradient(180deg, rgba(26, 42, 64, 0.98), rgba(12, 23, 39, 0.98))',
                '--brand-mark-border' => 'rgba(153, 198, 228, 0.18)',
                '--brand-mark-shadow' => '0 18px 34px rgba(2, 7, 16, 0.42)',
                '--brand-mark-filter' => 'saturate(0.82) hue-rotate(14deg) brightness(0.94) contrast(1.08)',
                '--tab-icon-chip' => 'rgba(76, 128, 168, 0.16)',
                '--tab-icon-chip-active' => 'rgba(92, 152, 198, 0.32)',
                '--tab-icon-filter' => 'saturate(0.92) hue-rotate(10deg) brightness(0.98)',
                '--tab-icon-filter-active' => 'saturate(1.14) hue-rotate(12deg) brightness(1.04)',
            ],
        ],
        'pier' => [
            'name' => 'Pier',
            'color' => '#0f1419',
            'tokens' => [
                '--bg'                => '#0f1419',
                '--surface'           => '#181410',
                '--border'            => '#2a2210',
                '--text-primary'      => '#e8d8a8',
                '--text-primary-dark' => '#f0e8c0',
                '--text-secondary'    => '#7a6a3a',
                '--text-muted'        => '#4a3a20',
                '--accent'            => '#c8a84c',
                '--done-bg'           => '#0a0e12',
                '--error'             => '#d05040',
                '--font-family'       => "Georgia, 'Times New Roman', serif",
                '--brand-mark-surface' => 'linear-gradient(180deg, rgba(34, 27, 18, 0.98), rgba(16, 19, 23, 0.98))',
                '--brand-mark-border' => 'rgba(200, 168, 76, 0.2)',
                '--brand-mark-shadow' => '0 18px 34px rgba(0, 0, 0, 0.42)',
                '--brand-mark-filter' => 'saturate(0.86) sepia(0.12) brightness(0.95) contrast(1.08)',
                '--tab-icon-chip' => 'rgba(200, 168, 76, 0.16)',
                '--tab-icon-chip-active' => 'rgba(200, 168, 76, 0.3)',
                '--tab-icon-filter' => 'saturate(0.98) sepia(0.08)',
                '--tab-icon-filter-active' => 'saturate(1.12) sepia(0.12)',
            ],
        ],
    ],
];