<?php
declare(strict_types=1);

$themeDataPath = dirname(__DIR__) . '/public/theme-data.php';
$outputPath = __DIR__ . '/theme-tokens.js';

if (!is_file($themeDataPath)) {
    fwrite(STDERR, "Theme-Daten nicht gefunden: {$themeDataPath}\n");
    exit(1);
}

$themeGroups = require $themeDataPath;
if (!is_array($themeGroups)) {
    fwrite(STDERR, "Theme-Daten haben ein unerwartetes Format.\n");
    exit(1);
}

$themes = [];
foreach (['light', 'dark'] as $mode) {
    foreach (($themeGroups[$mode] ?? []) as $key => $theme) {
        if (!is_array($theme)) {
            continue;
        }

        $themes[$key] = [
            'mode' => $mode,
            'name' => (string) ($theme['name'] ?? $key),
            'color' => (string) ($theme['color'] ?? ''),
            'tokens' => is_array($theme['tokens'] ?? null) ? $theme['tokens'] : [],
        ];
    }
}

$json = json_encode(
    $themes,
    JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE
);

if (!is_string($json)) {
    fwrite(STDERR, "Theme-Daten konnten nicht serialisiert werden.\n");
    exit(1);
}

$contents = <<<JS
// Generated by browser-extension/sync-theme-data.php
globalThis.ANKERKLADDE_THEMES = {$json};
JS;

if (file_put_contents($outputPath, $contents . PHP_EOL) === false) {
    fwrite(STDERR, "Theme-Datei konnte nicht geschrieben werden: {$outputPath}\n");
    exit(1);
}

fwrite(STDOUT, "Theme-Datei aktualisiert: {$outputPath}\n");
